# Generated by Django 5.2.8 on 2025-11-18 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, max_length=500, verbose_name='Bio'),
        ),
        migrations.AddField(
            model_name='user',
            name='karma',
            field=models.IntegerField(default=0, verbose_name='Karma Score'),
        ),
    ]
